name: Deploy Voilà App

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Voilà
        run: |
          pip install voila
      - name: Deploy to Voilà
        run: |
          voila --no-browser --port ${{ github.event.deployment.environment }} 0517 Event Summary Plot Generator.ipynb
